# Generated by Django 6.0.6 on 2026-06-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=50)),
                ('mileage', models.CharField(max_length=50)),
                ('fuel', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
            ],
        ),
    ]
